version: "3.8"

services:
  web:
    build: .
    container_name: accidents_web
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - ./.env
    ports:
      - "8010:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgis/postgis:13-3.1
    container_name: accidents_db
    restart: always
    env_file:
      - ./.env_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
